version: '3.8'

services:
  db:
    image: 17.5-alpine3.22    # Alpine-based PostgreSQL
    container_name: postgres
    restart: always
    shm_size: 128mb              # shared memory limit
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.0.3-alpine          # Alpine-based Redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: